#ifndef BITCOIN_HTTPSERVER_H
#define BITCOIN_HTTPSERVER_H

static const int DEFAULT_HTTP_THREADS=4;
static const int DEFAULT_HTTP_WORKQUEUE=16;
static const int DEFAULT_HTTP_SERVER_TIMEOUT=30;

#endif // BITCOIN_HTTPSERVER_H
